// <auto-generated />
using System;
using Jess.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jess.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ArquivoProjeto", b =>
                {
                    b.Property<int>("ArquivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjetosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArquivoId", "ProjetosId");

                    b.HasIndex("ProjetosId");

                    b.ToTable("ArquivoProjeto", (string)null);
                });

            modelBuilder.Entity("ArquivoTag", b =>
                {
                    b.Property<int>("ArquivosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArquivosId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ArquivoTag", (string)null);
                });

            modelBuilder.Entity("Jess.Entities.Entities.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Favorito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoArquivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeArquiteto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataRecebimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorRecebido")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Jess.Entities.Entities.PausaRegistroHoras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FimPausa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioPausa")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistroHorasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegistroHorasId");

                    b.ToTable("PausasRegistroHoras");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PrazoEstimado")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotalAcordado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("Jess.Entities.Entities.RegistroDeHoras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FimSessao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioSessao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("RegistrosDeHoras");
                });

            modelBuilder.Entity("Jess.Entities.Entities.SegmentoHoras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegistroHorasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegistroHorasId");

                    b.ToTable("SegmentosHoras");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Subtarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarefaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("Subtarefas");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coluna")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Fase")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegraRecorrencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("ArquivoProjeto", b =>
                {
                    b.HasOne("Jess.Entities.Entities.Arquivo", null)
                        .WithMany()
                        .HasForeignKey("ArquivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jess.Entities.Entities.Projeto", null)
                        .WithMany()
                        .HasForeignKey("ProjetosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquivoTag", b =>
                {
                    b.HasOne("Jess.Entities.Entities.Arquivo", null)
                        .WithMany()
                        .HasForeignKey("ArquivosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jess.Entities.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jess.Entities.Entities.Pagamento", b =>
                {
                    b.HasOne("Jess.Entities.Entities.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Jess.Entities.Entities.PausaRegistroHoras", b =>
                {
                    b.HasOne("Jess.Entities.Entities.RegistroDeHoras", "RegistroHoras")
                        .WithMany("Pausas")
                        .HasForeignKey("RegistroHorasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroHoras");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Projeto", b =>
                {
                    b.HasOne("Jess.Entities.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Jess.Entities.Entities.RegistroDeHoras", b =>
                {
                    b.HasOne("Jess.Entities.Entities.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Jess.Entities.Entities.SegmentoHoras", b =>
                {
                    b.HasOne("Jess.Entities.Entities.RegistroDeHoras", "RegistroHoras")
                        .WithMany("Segmentos")
                        .HasForeignKey("RegistroHorasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroHoras");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Subtarefa", b =>
                {
                    b.HasOne("Jess.Entities.Entities.Tarefa", "Tarefa")
                        .WithMany("Subtarefas")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Tarefa", b =>
                {
                    b.HasOne("Jess.Entities.Entities.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Jess.Entities.Entities.RegistroDeHoras", b =>
                {
                    b.Navigation("Pausas");

                    b.Navigation("Segmentos");
                });

            modelBuilder.Entity("Jess.Entities.Entities.Tarefa", b =>
                {
                    b.Navigation("Subtarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
